/**
 * Permission Constants
 * Definisi semua permission dalam sistem
 */

export const PERMISSIONS = {
  // Letter Management
  LETTER_CREATE: 'letter:create',
  LETTER_READ: 'letter:read',
  LETTER_UPDATE: 'letter:update',
  LETTER_DELETE: 'letter:delete',
  LETTER_APPROVE: 'letter:approve',
  LETTER_REJECT: 'letter:reject',
  LETTER_SIGN: 'letter:sign',
  LETTER_DISPOSITION: 'letter:disposition',
  LETTER_VERIFY: 'letter:verify',
  LETTER_DRAFT: 'letter:draft',
  LETTER_RETURN: 'letter:return',
  LETTER_COMPLETE: 'letter:complete',
  
  // UPA Actions
  UPA_NUMBER: 'upa:number',
  UPA_STAMP: 'upa:stamp',
  UPA_FINALIZE: 'upa:finalize',
  
  // Dashboard
  DASHBOARD_VIEW_ALL: 'dashboard:view_all',
  DASHBOARD_VIEW_OWN: 'dashboard:view_own',
  DASHBOARD_VIEW_DEPARTMENT: 'dashboard:view_department',
  DASHBOARD_VIEW_FACULTY: 'dashboard:view_faculty',
  
  // Master Data
  MASTER_MANAGE: 'master:manage',
  MASTER_READ: 'master:read',
  
  // User Management
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  
  // System
  SYSTEM_ADMIN: 'system:admin',
} as const;

export type PermissionName = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/**
 * Default permissions per role
 */
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPERADMIN: Object.values(PERMISSIONS),
  
  MAHASISWA: [
    PERMISSIONS.LETTER_CREATE,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.DASHBOARD_VIEW_OWN,
  ],
  
  DOSEN: [
    PERMISSIONS.LETTER_CREATE,
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.DASHBOARD_VIEW_OWN,
  ],
  
  KAPRODI: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_APPROVE,
    PERMISSIONS.LETTER_REJECT,
    PERMISSIONS.LETTER_SIGN,
    PERMISSIONS.LETTER_RETURN,
    PERMISSIONS.DASHBOARD_VIEW_DEPARTMENT,
  ],
  
  ADMIN_PRODI: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_DRAFT,
    PERMISSIONS.LETTER_UPDATE,
    PERMISSIONS.DASHBOARD_VIEW_DEPARTMENT,
  ],
  
  KADEP: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_SIGN,
    PERMISSIONS.DASHBOARD_VIEW_DEPARTMENT,
  ],
  
  ADMIN_FAKULTAS: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_DISPOSITION,
    PERMISSIONS.LETTER_RETURN,
    PERMISSIONS.DASHBOARD_VIEW_FACULTY,
  ],
  
  DEKAN: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_DISPOSITION,
    PERMISSIONS.LETTER_VERIFY,
    PERMISSIONS.LETTER_SIGN,
    PERMISSIONS.LETTER_COMPLETE,
    PERMISSIONS.LETTER_RETURN,
    PERMISSIONS.DASHBOARD_VIEW_FACULTY,
  ],
  
  WADEK_1: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_DISPOSITION,
    PERMISSIONS.LETTER_VERIFY,
    PERMISSIONS.LETTER_SIGN,
    PERMISSIONS.LETTER_RETURN,
    PERMISSIONS.DASHBOARD_VIEW_FACULTY,
  ],
  
  WADEK_2: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_DISPOSITION,
    PERMISSIONS.LETTER_VERIFY,
    PERMISSIONS.LETTER_SIGN,
    PERMISSIONS.LETTER_RETURN,
    PERMISSIONS.DASHBOARD_VIEW_FACULTY,
  ],
  
  MANAJER_TU: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_DISPOSITION,
    PERMISSIONS.LETTER_VERIFY,
    PERMISSIONS.LETTER_RETURN,
    PERMISSIONS.DASHBOARD_VIEW_FACULTY,
  ],
  
  SUPERVISOR_AKADEMIK: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_DISPOSITION,
    PERMISSIONS.LETTER_VERIFY,
    PERMISSIONS.LETTER_DRAFT,
    PERMISSIONS.LETTER_RETURN,
    PERMISSIONS.DASHBOARD_VIEW_FACULTY,
  ],
  
  SUPERVISOR_SUMBER_DAYA: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_DISPOSITION,
    PERMISSIONS.LETTER_VERIFY,
    PERMISSIONS.LETTER_DRAFT,
    PERMISSIONS.LETTER_RETURN,
    PERMISSIONS.DASHBOARD_VIEW_FACULTY,
  ],
  
  STAF_AKADEMIK: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_DRAFT,
    PERMISSIONS.LETTER_UPDATE,
    PERMISSIONS.LETTER_VERIFY,
    PERMISSIONS.DASHBOARD_VIEW_FACULTY,
  ],
  
  STAF_SUMBER_DAYA: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.LETTER_DRAFT,
    PERMISSIONS.LETTER_UPDATE,
    PERMISSIONS.LETTER_VERIFY,
    PERMISSIONS.DASHBOARD_VIEW_FACULTY,
  ],
  
  UPA: [
    PERMISSIONS.LETTER_READ,
    PERMISSIONS.UPA_NUMBER,
    PERMISSIONS.UPA_STAMP,
    PERMISSIONS.UPA_FINALIZE,
    PERMISSIONS.DASHBOARD_VIEW_FACULTY,
  ],
};

/**
 * Check if role has permission
 */
export function hasPermission(role: string, permission: string): boolean {
  const permissions = ROLE_PERMISSIONS[role];
  if (!permissions) return false;
  return permissions.includes(permission);
}
